const linkData = [
    { ans: "Lionel Messi", alias: ["messi", "leo messi"], teammates: ["Xavi Hernández", "Neymar Jr", "Kylian Mbappé", "Sergio Agüero"] },
    { ans: "Cristiano Ronaldo", alias: ["cristiano", "ronaldo", "cr7"], teammates: ["Wayne Rooney", "Karim Benzema", "Paulo Dybala", "Sadio Mané"] },
    { ans: "Ángel Di María", alias: ["di maria", "angel di maria", "fideo"], teammates: ["Marcelo", "Zlatan Ibrahimovic", "Gianluigi Buffon", "Enzo Fernández"] },
    { ans: "Zlatan Ibrahimović", alias: ["zlatan", "ibrahimovic"], teammates: ["Patrick Vieira", "Thiago Silva", "Edinson Cavani", "Theo Hernández"] },
    { ans: "Luis Suárez", alias: ["suarez", "luis suarez"], teammates: ["Steven Gerrard", "Lionel Messi", "Diego Godín", "Jordan Henderson"] },
    { ans: "Neymar Jr", alias: ["neymar", "ney"], teammates: ["Ganso", "Andrés Iniesta", "Sergio Ramos", "Kalidou Koulibaly"] },
    { ans: "Gonzalo Higuaín", alias: ["higuain", "pipita"], teammates: ["Raúl González", "Marek Hamsik", "Eden Hazard", "Blaise Matuidi"] },
    { ans: "Sergio Agüero", alias: ["aguero", "kun"], teammates: ["Diego Forlán", "David Silva", "Nicolas Otamendi", "Phil Foden"] },
    { ans: "Ronaldinho", alias: ["ronaldinho", "dinho"], teammates: ["Ronaldo Nazário", "Carles Puyol", "Andrea Pirlo", "Zlatan Ibrahimovic"] },
    { ans: "Ronaldo Nazário", alias: ["ronaldo", "fenomeno"], teammates: ["Luís Figo", "Zinedine Zidane", "Paolo Maldini", "Roberto Baggio"] },
    { ans: "Enzo Fernández", alias: ["enzo fernandez", "enzo"], teammates: ["Julián Álvarez", "João Félix", "Nicolas Jackson", "Thiago Silva"] },
    { ans: "Julián Álvarez", alias: ["julian alvarez", "araña"], teammates: ["Enzo Pérez", "Erling Haaland", "Antoine Griezmann", "Rodrigo De Paul"] },
    { ans: "Kylian Mbappé", alias: ["mbappe"], teammates: ["Bernardo Silva", "Lionel Messi", "Vinícius Júnior", "Luka Modric"] },
    { ans: "Erling Haaland", alias: ["haaland"], teammates: ["Jadon Sancho", "Marco Reus", "Kevin De Bruyne", "Phil Foden"] },
    { ans: "Luka Modrić", alias: ["modric"], teammates: ["Gareth Bale", "Karim Benzema", "Ivan Perisic", "Casemiro"] },
    { ans: "Karim Benzema", alias: ["benzema"], teammates: ["Juninho Pernambucano", "Cristiano Ronaldo", "Vinícius Júnior", "N'Golo Kanté"] },
    { ans: "Robert Lewandowski", alias: ["lewandowski"], teammates: ["Thomas Müller", "Manuel Neuer", "Pedri", "İlkay Gündoğan"] },
    { ans: "Alexis Sánchez", alias: ["alexis sanchez", "alexis"], teammates: ["Cesc Fàbregas", "Mesut Özil", "Lautaro Martínez", "Arturo Vidal"] },
    { ans: "Arturo Vidal", alias: ["vidal", "rey arturo"], teammates: ["Andrea Pirlo", "Robert Lewandowski", "Lionel Messi", "Gary Medel"] },
    { ans: "Paulo Dybala", alias: ["dybala", "joya"], teammates: ["Paul Pogba", "Cristiano Ronaldo", "Tammy Abraham", "Leandro Paredes"] },
    { ans: "Thierry Henry", alias: ["henry", "titi"], teammates: ["Dennis Bergkamp", "Patrick Vieira", "Lionel Messi", "Ronaldinho"] },
    { ans: "David Beckham", alias: ["beckham"], teammates: ["Ryan Giggs", "Roberto Carlos", "Landon Donovan", "Zlatan Ibrahimovic"] },
    { ans: "Wayne Rooney", alias: ["rooney"], teammates: ["Cristiano Ronaldo", "Rio Ferdinand", "Harry Kane", "Bastian Schweinsteiger"] },
    { ans: "Mesut Özil", alias: ["ozil"], teammates: ["Cristiano Ronaldo", "Alexis Sánchez", "Santi Cazorla", "Thomas Müller"] },
    { ans: "N'Golo Kanté", alias: ["kante"], teammates: ["Riyad Mahrez", "Eden Hazard", "Karim Benzema", "Paul Pogba"] },
    { ans: "Gianluigi Buffon", alias: ["buffon", "gigi"], teammates: ["Lilian Thuram", "Alessandro Del Piero", "Ángel Di María", "Kylian Mbappé"] },
    { ans: "Andrea Pirlo", alias: ["pirlo", "maestro"], teammates: ["Filippo Inzaghi", "Clarence Seedorf", "Paul Pogba", "David Villa"] },
    { ans: "Cesc Fàbregas", alias: ["fabregas"], teammates: ["Thierry Henry", "Lionel Messi", "Eden Hazard", "Radamel Falcao"] },
    { ans: "Radamel Falcao", alias: ["falcao", "tigre"], teammates: ["James Rodríguez", "Diego Costa", "Wayne Rooney", "Kylian Mbappé"] },
    { ans: "James Rodríguez", alias: ["james"], teammates: ["Hulk", "Cristiano Ronaldo", "Robert Lewandowski", "Richarlison"] },
    { ans: "Manuel Neuer", alias: ["neuer"], teammates: ["Raúl González", "Philipp Lahm", "Robert Lewandowski", "Harry Kane"] },
    { ans: "Toni Kroos", alias: ["kroos"], teammates: ["Miroslav Klose", "Cristiano Ronaldo", "Luka Modrić", "Vinícius Júnior"] },
    { ans: "Sergio Ramos", alias: ["ramos", "sergio ramos"], teammates: ["Jesús Navas", "Iker Casillas", "Lionel Messi", "Kylian Mbappé"] },
    { ans: "Antoine Griezmann", alias: ["griezmann"], teammates: ["Diego Godín", "Lionel Messi", "Julián Álvarez", "Paul Pogba"] },
    { ans: "Vinícius Júnior", alias: ["vinicius", "vini"], teammates: ["Casemiro", "Karim Benzema", "Jude Bellingham", "Neymar Jr"] },
    { ans: "Jude Bellingham", alias: ["bellingham"], teammates: ["Erling Haaland", "Harry Kane", "Vinícius Júnior", "Marco Reus"] },
    { ans: "Lautaro Martínez", alias: ["lautaro", "toro"], teammates: ["Mauro Icardi", "Romelu Lukaku", "Lionel Messi", "Alexis Sánchez"] },
    { ans: "Rodrigo De Paul", alias: ["de paul"], teammates: ["Ángel Correa", "Luis Suárez", "Lionel Messi", "Enzo Pérez"] },
    { ans: "Emiliano Martínez", alias: ["dibu", "dibu martinez"], teammates: ["Jack Grealish", "Mesut Özil", "Lionel Messi", "Ollie Watkins"] },
    { ans: "Paolo Maldini", alias: ["maldini"], teammates: ["Franco Baresi", "Andriy Shevchenko", "Kaká", "Ronaldo Nazário"] },
    { ans: "Francesco Totti", alias: ["totti"], teammates: ["Gabriel Batistuta", "Daniele De Rossi", "Mohamed Salah", "Alisson Becker"] },
    { ans: "Alessandro Del Piero", alias: ["del piero"], teammates: ["Roberto Baggio", "Zinedine Zidane", "David Trezeguet", "Gianluigi Buffon"] },
    { ans: "Roberto Carlos", alias: ["roberto carlos"], teammates: ["Ronaldo Nazário", "Zinedine Zidane", "David Beckham", "Raúl González"] },
    { ans: "Cafu", alias: ["cafu"], teammates: ["Gabriel Batistuta", "Francesco Totti", "Paolo Maldini", "Ronaldinho"] },
    { ans: "Rivaldo", alias: ["rivaldo"], teammates: ["Patrick Kluivert", "Ronaldo Nazário", "Paolo Maldini", "Ronaldinho"] },
    { ans: "Romário", alias: ["romario"], teammates: ["Hristo Stoichkov", "Pep Guardiola", "Ronaldo Nazário", "Bebeto"] },
    { ans: "Roberto Baggio", alias: ["baggio"], teammates: ["Alessandro Del Piero", "George Weah", "Ronaldo Nazário", "Pep Guardiola"] },
    { ans: "Ruud Gullit", alias: ["gullit"], teammates: ["Marco van Basten", "Frank Rijkaard", "Franco Baresi", "Gianfranco Zola"] },
    { ans: "Marco van Basten", alias: ["van basten"], teammates: ["Frank Rijkaard", "Ruud Gullit", "Franco Baresi", "Paolo Maldini"] },
    { ans: "Franco Baresi", alias: ["baresi"], teammates: ["Paolo Maldini", "Ruud Gullit", "Marco van Basten", "Alessandro Costacurta"] },
    { ans: "Lothar Matthäus", alias: ["matthaus"], teammates: ["Andreas Brehme", "Jürgen Klinsmann", "Oliver Kahn", "Stefan Effenberg"] },
    { ans: "Michel Platini", alias: ["platini"], teammates: ["Paolo Rossi", "Gaetano Scirea", "Zbigniew Boniek", "Jean Tigana"] },
    { ans: "Sócrates", alias: ["socrates"], teammates: ["Zico", "Falcao", "Junior", "Casagrande"] },
    { ans: "Zico", alias: ["zico"], teammates: ["Sócrates", "Junior", "Leovegildo Lins da Gama", "Toninho Cerezo"] },
    { ans: "Hugo Sánchez", alias: ["hugo sanchez"], teammates: ["Emilio Butragueño", "Míchel", "Jorge Valdano", "Oscar Ruggeri"] },
    { ans: "Enzo Francescoli", alias: ["francescoli", "principe"], teammates: ["Ariel Ortega", "Hernán Crespo", "Zinedine Zidane", "Jean-Pierre Papin"] },
    { ans: "Jorge Valdano", alias: ["valdano"], teammates: ["Diego Maradona", "Hugo Sánchez", "Emilio Butragueño", "Oscar Ruggeri"] },
    { ans: "Oscar Ruggeri", alias: ["ruggeri", "cabezon"], teammates: ["Diego Maradona", "Hugo Sánchez", "Ricardo Bochini", "Claudio Caniggia"] },
    { ans: "Claudio Caniggia", alias: ["caniggia"], teammates: ["Diego Maradona", "Gabriel Batistuta", "Ariel Ortega", "Juan Román Riquelme"] },
    { ans: "Ariel Ortega", alias: ["ortega", "burrito"], teammates: ["Enzo Francescoli", "Gabriel Batistuta", "Juan Sebastián Verón", "Hernán Crespo"] },
    { ans: "Juan Sebastián Verón", alias: ["veron", "brujita"], teammates: ["Hernán Crespo", "Diego Simeone", "David Beckham", "Lionel Messi"] },
    { ans: "Esteban Cambiasso", alias: ["cambiasso", "cuchu"], teammates: ["Javier Zanetti", "Diego Milito", "Zlatan Ibrahimovic", "Wesley Sneijder"] },
    { ans: "Javier Zanetti", alias: ["zanetti", "pupi"], teammates: ["Roberto Baggio", "Ronaldo Nazário", "Zlatan Ibrahimovic", "Diego Milito"] },
    { ans: "Roberto Ayala", alias: ["ayala", "raton"], teammates: ["Pablo Aimar", "Juan Román Riquelme", "Claudio López", "Gabriel Batistuta"] },
    { ans: "Walter Samuel", alias: ["samuel", "muro"], teammates: ["Francesco Totti", "Zinedine Zidane", "Javier Zanetti", "Diego Milito"] },
    { ans: "Gabriel Milito", alias: ["milito", "mariscal"], teammates: ["Lionel Messi", "Carles Puyol", "Ronaldinho", "Pablo Aimar"] },
    { ans: "Pablo Aimar", alias: ["aimar", "payaso"], teammates: ["Javier Saviola", "Roberto Ayala", "Lionel Messi", "Juan Román Riquelme"] },
    { ans: "Michael Owen", alias: ["owen"], teammates: ["Steven Gerrard", "Zinedine Zidane", "Wayne Rooney", "Alan Shearer"] },
    { ans: "Steven Gerrard", alias: ["gerrard"], teammates: ["Luis Suárez", "Fernando Torres", "Jamie Carragher", "Xabi Alonso"] },
    { ans: "Frank Lampard", alias: ["lampard"], teammates: ["John Terry", "Didier Drogba", "Petr Čech", "Sergio Agüero"] },
    { ans: "Paul Scholes", alias: ["scholes"], teammates: ["Ryan Giggs", "David Beckham", "Cristiano Ronaldo", "Wayne Rooney"] },
    { ans: "Clarence Seedorf", alias: ["seedorf"], teammates: ["Patrick Kluivert", "Roberto Carlos", "Andrea Pirlo", "Kaká"] },
    { ans: "Edgar Davids", alias: ["davids", "pitbull"], teammates: ["Zinedine Zidane", "Patrick Kluivert", "Alessandro Del Piero", "Ronaldinho"] },
    { ans: "Deco", alias: ["deco"], teammates: ["Ricardo Carvalho", "Ronaldinho", "Lionel Messi", "Frank Lampard"] },
    { ans: "Luís Figo", alias: ["figo"], teammates: ["Rui Costa", "Zinedine Zidane", "Ronaldo Nazário", "Javier Zanetti"] },
    { ans: "Patrick Vieira", alias: ["vieira"], teammates: ["Thierry Henry", "Dennis Bergkamp", "Zlatan Ibrahimovic", "Mario Balotelli"] },
    { ans: "Claude Makélélé", alias: ["makelele"], teammates: ["Zinedine Zidane", "Frank Lampard", "Didier Drogba", "Eden Hazard"] },
    { ans: "Michael Ballack", alias: ["ballack"], teammates: ["Oliver Kahn", "Didier Drogba", "Frank Lampard", "Bastian Schweinsteiger"] },
    { ans: "Oliver Kahn", alias: ["kahn", "titan"], teammates: ["Lothar Matthäus", "Michael Ballack", "Bastian Schweinsteiger", "Philipp Lahm"] },
    { ans: "Peter Schmeichel", alias: ["schmeichel"], teammates: ["Eric Cantona", "Ryan Giggs", "Paul Scholes", "James Milner"] },
    { ans: "Edwin van der Sar", alias: ["van der sar"], teammates: ["Patrick Kluivert", "Alessandro Del Piero", "Cristiano Ronaldo", "Wayne Rooney"] },
    { ans: "Petr Čech", alias: ["cech"], teammates: ["John Terry", "Frank Lampard", "Didier Drogba", "Mesut Özil"] },
    { ans: "Iker Casillas", alias: ["casillas"], teammates: ["Zinedine Zidane", "Cristiano Ronaldo", "Sergio Ramos", "Pepe"] },
    { ans: "Xavi Hernández", alias: ["xavi"], teammates: ["Andrés Iniesta", "Lionel Messi", "Samuel Eto'o", "David Villa"] },
    { ans: "Andrés Iniesta", alias: ["iniesta"], teammates: ["Xavi Hernández", "Lionel Messi", "Neymar Jr", "Fernando Torres"] },
    { ans: "Carles Puyol", alias: ["puyol"], teammates: ["Luis Enrique", "Ronaldinho", "Xavi Hernández", "Lionel Messi"] },
    { ans: "Alessandro Nesta", alias: ["nesta"], teammates: ["Juan Sebastián Verón", "Paolo Maldini", "Andrea Pirlo", "Kaká"] },
    { ans: "Filippo Inzaghi", alias: ["inzaghi", "pippo"], teammates: ["Alessandro Del Piero", "Zinedine Zidane", "Andrea Pirlo", "Kaká"] },
    { ans: "Christian Vieri", alias: ["vieri", "bobo"], teammates: ["Ronaldo Nazário", "Alessandro Del Piero", "Roberto Baggio", "Hernán Crespo"] },
    { ans: "Fabio Cannavaro", alias: ["cannavaro"], teammates: ["Lilian Thuram", "Gianluigi Buffon", "Iker Casillas", "Cristiano Ronaldo"] },
    { ans: "Pavel Nedvěd", alias: ["nedved"], teammates: ["Alessandro Del Piero", "David Trezeguet", "Zlatan Ibrahimovic", "Juan Sebastián Verón"] },
    { ans: "David Villa", alias: ["villa", "guaje"], teammates: ["David Silva", "Xavi Hernández", "Lionel Messi", "Fernando Torres"] },
    { ans: "Arjen Robben", alias: ["robben"], teammates: ["Frank Lampard", "Wesley Sneijder", "Franck Ribéry", "Robert Lewandowski"] },
    { ans: "Franck Ribéry", alias: ["ribery"], teammates: ["Zinedine Zidane", "Arjen Robben", "Thomas Müller", "Robert Lewandowski"] },
    { ans: "Thomas Müller", alias: ["muller"], teammates: ["Miroslav Klose", "Arjen Robben", "Robert Lewandowski", "Harry Kane"] },
    { ans: "Philipp Lahm", alias: ["lahm"], teammates: ["Michael Ballack", "Bastian Schweinsteiger", "Arjen Robben", "Franck Ribéry"] },
    { ans: "Bastian Schweinsteiger", alias: ["schweinsteiger"], teammates: ["Oliver Kahn", "Michael Ballack", "Wayne Rooney", "Zlatan Ibrahimovic"] },
    { ans: "Miroslav Klose", alias: ["klose"], teammates: ["Michael Ballack", "Thomas Müller", "Toni Kroos", "Hernán Crespo"] },
    { ans: "Gianluigi Donnarumma", alias: ["donnarumma", "gigio"], teammates: ["Zlatan Ibrahimovic", "Lionel Messi", "Kylian Mbappé", "Marco Verratti"] },
    { ans: "Rodri", alias: ["rodri"], teammates: ["Antoine Griezmann", "Kevin De Bruyne", "Erling Haaland", "Lamine Yamal"] }
];