const resultadoData = [
    { date: "18/12/2022", competition: "Mundial 2022 - Final", home: "Argentina", away: "Francia", homeScore: 3, awayScore: 3, note: "Argentina gano por penales." },
    { date: "15/07/2018", competition: "Mundial 2018 - Final", home: "Francia", away: "Croacia", homeScore: 4, awayScore: 2, note: "Final en Moscu." },
    { date: "13/07/2014", competition: "Mundial 2014 - Final", home: "Alemania", away: "Argentina", homeScore: 1, awayScore: 0, note: "Gol de Gotze en el suplementario." },
    { date: "11/07/2010", competition: "Mundial 2010 - Final", home: "Espana", away: "Paises Bajos", homeScore: 1, awayScore: 0, note: "Gol de Iniesta." },
    { date: "09/07/2006", competition: "Mundial 2006 - Final", home: "Italia", away: "Francia", homeScore: 1, awayScore: 1, note: "Italia gano por penales." },
    { date: "08/07/2014", competition: "Mundial 2014 - Semifinal", home: "Brasil", away: "Alemania", homeScore: 1, awayScore: 7, note: "El Mineirazo." },
    { date: "13/12/2022", competition: "Mundial 2022 - Semifinal", home: "Argentina", away: "Croacia", homeScore: 3, awayScore: 0, note: "Argentina paso a la final." },
    { date: "14/12/2022", competition: "Mundial 2022 - Semifinal", home: "Francia", away: "Marruecos", homeScore: 2, awayScore: 0, note: "Francia defendio el titulo hasta la final." },
    { date: "09/12/2022", competition: "Mundial 2022 - Cuartos", home: "Argentina", away: "Paises Bajos", homeScore: 2, awayScore: 2, note: "Argentina gano por penales." },
    { date: "15/06/2018", competition: "Mundial 2018 - Grupo", home: "Portugal", away: "Espana", homeScore: 3, awayScore: 3, note: "Hat-trick de Cristiano Ronaldo." },
    { date: "30/06/2018", competition: "Mundial 2018 - Octavos", home: "Francia", away: "Argentina", homeScore: 4, awayScore: 3, note: "Partidazo en Kazan." },
    { date: "02/07/2018", competition: "Mundial 2018 - Octavos", home: "Belgica", away: "Japon", homeScore: 3, awayScore: 2, note: "Remontada belga." },
    { date: "22/11/2022", competition: "Mundial 2022 - Grupo", home: "Argentina", away: "Arabia Saudita", homeScore: 1, awayScore: 2, note: "Sorpresa en Lusail." },
    { date: "01/12/2022", competition: "Mundial 2022 - Grupo", home: "Japon", away: "Espana", homeScore: 2, awayScore: 1, note: "Japon gano el grupo." },
    { date: "10/12/2022", competition: "Mundial 2022 - Cuartos", home: "Marruecos", away: "Portugal", homeScore: 1, awayScore: 0, note: "Marruecos hizo historia." },
    { date: "09/12/2022", competition: "Mundial 2022 - Cuartos", home: "Croacia", away: "Brasil", homeScore: 1, awayScore: 1, note: "Croacia gano por penales." },
    { date: "04/07/2015", competition: "Copa America 2015 - Final", home: "Chile", away: "Argentina", homeScore: 0, awayScore: 0, note: "Chile gano por penales." },
    { date: "26/06/2016", competition: "Copa America 2016 - Final", home: "Argentina", away: "Chile", homeScore: 0, awayScore: 0, note: "Chile gano por penales." },
    { date: "07/07/2019", competition: "Copa America 2019 - Final", home: "Brasil", away: "Peru", homeScore: 3, awayScore: 1, note: "Brasil campeon en el Maracana." },
    { date: "10/07/2021", competition: "Copa America 2021 - Final", home: "Argentina", away: "Brasil", homeScore: 1, awayScore: 0, note: "Gol de Di Maria." },
    { date: "14/07/2024", competition: "Copa America 2024 - Final", home: "Argentina", away: "Colombia", homeScore: 1, awayScore: 0, note: "Gol de Lautaro Martinez en el suplementario." },
    { date: "10/07/2016", competition: "Euro 2016 - Final", home: "Portugal", away: "Francia", homeScore: 1, awayScore: 0, note: "Gol de Eder." },
    { date: "11/07/2021", competition: "Euro 2020 - Final", home: "Italia", away: "Inglaterra", homeScore: 1, awayScore: 1, note: "Italia gano por penales." },
    { date: "14/07/2024", competition: "Euro 2024 - Final", home: "Espana", away: "Inglaterra", homeScore: 2, awayScore: 1, note: "Espana campeona en Berlin." },
    { date: "01/07/2024", competition: "Copa America 2024 - Grupo", home: "Estados Unidos", away: "Uruguay", homeScore: 0, awayScore: 1, note: "Uruguay gano su zona." },
    { date: "06/06/2015", competition: "Champions League 2015 - Final", home: "Barcelona", away: "Juventus", homeScore: 3, awayScore: 1, note: "Final en Berlin." },
    { date: "28/05/2016", competition: "Champions League 2016 - Final", home: "Real Madrid", away: "Atletico de Madrid", homeScore: 1, awayScore: 1, note: "Real Madrid gano por penales." },
    { date: "03/06/2017", competition: "Champions League 2017 - Final", home: "Real Madrid", away: "Juventus", homeScore: 4, awayScore: 1, note: "Doblete de Cristiano." },
    { date: "26/05/2018", competition: "Champions League 2018 - Final", home: "Real Madrid", away: "Liverpool", homeScore: 3, awayScore: 1, note: "Chilena de Bale." },
    { date: "01/06/2019", competition: "Champions League 2019 - Final", home: "Liverpool", away: "Tottenham", homeScore: 2, awayScore: 0, note: "Final inglesa en Madrid." },
    { date: "23/08/2020", competition: "Champions League 2020 - Final", home: "Bayern Munich", away: "PSG", homeScore: 1, awayScore: 0, note: "Gol de Coman." },
    { date: "29/05/2021", competition: "Champions League 2021 - Final", home: "Chelsea", away: "Manchester City", homeScore: 1, awayScore: 0, note: "Gol de Havertz." },
    { date: "28/05/2022", competition: "Champions League 2022 - Final", home: "Real Madrid", away: "Liverpool", homeScore: 1, awayScore: 0, note: "Gol de Vinicius." },
    { date: "10/06/2023", competition: "Champions League 2023 - Final", home: "Manchester City", away: "Inter", homeScore: 1, awayScore: 0, note: "Gol de Rodri." },
    { date: "01/06/2024", competition: "Champions League 2024 - Final", home: "Borussia Dortmund", away: "Real Madrid", homeScore: 0, awayScore: 2, note: "Real Madrid gano la 15." },
    { date: "08/03/2017", competition: "Champions League 2017 - Octavos", home: "Barcelona", away: "PSG", homeScore: 6, awayScore: 1, note: "La remontada." },
    { date: "14/08/2020", competition: "Champions League 2020 - Cuartos", home: "Barcelona", away: "Bayern Munich", homeScore: 2, awayScore: 8, note: "Noche historica en Lisboa." },
    { date: "07/05/2019", competition: "Champions League 2019 - Semifinal", home: "Liverpool", away: "Barcelona", homeScore: 4, awayScore: 0, note: "Corner taken quickly." },
    { date: "10/04/2018", competition: "Champions League 2018 - Cuartos", home: "Roma", away: "Barcelona", homeScore: 3, awayScore: 0, note: "Roma paso por goles de visitante." },
    { date: "17/05/2023", competition: "Champions League 2023 - Semifinal", home: "Manchester City", away: "Real Madrid", homeScore: 4, awayScore: 0, note: "City paso a la final." },
    { date: "06/05/2015", competition: "Champions League 2015 - Semifinal", home: "Barcelona", away: "Bayern Munich", homeScore: 3, awayScore: 0, note: "Messi, Boateng y una noche enorme." },
    { date: "25/05/2005", competition: "Champions League 2005 - Final", home: "Liverpool", away: "Milan", homeScore: 3, awayScore: 3, note: "Liverpool gano por penales." },
    { date: "26/05/1999", competition: "Champions League 1999 - Final", home: "Manchester United", away: "Bayern Munich", homeScore: 2, awayScore: 1, note: "Remontada en el descuento." },
    { date: "24/05/2014", competition: "Champions League 2014 - Final", home: "Real Madrid", away: "Atletico de Madrid", homeScore: 4, awayScore: 1, note: "La Decima." },
    { date: "27/05/2009", competition: "Champions League 2009 - Final", home: "Barcelona", away: "Manchester United", homeScore: 2, awayScore: 0, note: "Final en Roma." },
    { date: "28/05/2011", competition: "Champions League 2011 - Final", home: "Barcelona", away: "Manchester United", homeScore: 3, awayScore: 1, note: "Final en Wembley." },
    { date: "05/08/2015", competition: "Libertadores 2015 - Final", leg: "Vuelta", home: "River Plate", away: "Tigres", homeScore: 3, awayScore: 0, note: "River campeon de America." },
    { date: "27/07/2016", competition: "Libertadores 2016 - Final", leg: "Vuelta", home: "Atletico Nacional", away: "Independiente del Valle", homeScore: 1, awayScore: 0, note: "Vuelta de la final." },
    { date: "29/11/2017", competition: "Libertadores 2017 - Final", leg: "Vuelta", home: "Lanus", away: "Gremio", homeScore: 1, awayScore: 2, note: "Gremio campeon." },
    { date: "11/11/2018", competition: "Libertadores 2018 - Final", leg: "Ida", home: "Boca Juniors", away: "River Plate", homeScore: 2, awayScore: 2, note: "Primera final de la superfinal." },
    { date: "09/12/2018", competition: "Libertadores 2018 - Final", leg: "Vuelta", home: "River Plate", away: "Boca Juniors", homeScore: 3, awayScore: 1, note: "Final de Madrid." },
    { date: "23/11/2019", competition: "Libertadores 2019 - Final", home: "River Plate", away: "Flamengo", homeScore: 1, awayScore: 2, note: "Remontada de Flamengo en Lima." },
    { date: "30/01/2021", competition: "Libertadores 2020 - Final", home: "Palmeiras", away: "Santos", homeScore: 1, awayScore: 0, note: "Final brasilena." },
    { date: "27/11/2021", competition: "Libertadores 2021 - Final", home: "Palmeiras", away: "Flamengo", homeScore: 2, awayScore: 1, note: "Palmeiras bicampeon." },
    { date: "29/10/2022", competition: "Libertadores 2022 - Final", home: "Flamengo", away: "Athletico Paranaense", homeScore: 1, awayScore: 0, note: "Gol de Gabigol." },
    { date: "04/11/2023", competition: "Libertadores 2023 - Final", home: "Fluminense", away: "Boca Juniors", homeScore: 2, awayScore: 1, note: "Final en el Maracana." },
    { date: "30/11/2024", competition: "Libertadores 2024 - Final", home: "Atletico Mineiro", away: "Botafogo", homeScore: 1, awayScore: 3, note: "Botafogo campeon." },
    { date: "14/05/2015", competition: "Libertadores 2015 - Octavos", leg: "Ida", home: "River Plate", away: "Boca Juniors", homeScore: 1, awayScore: 0, note: "Ida de octavos." },
    { date: "27/05/2015", competition: "Libertadores 2015 - Cuartos", leg: "Vuelta", home: "Cruzeiro", away: "River Plate", homeScore: 0, awayScore: 3, note: "River dio vuelta la serie." },
    { date: "31/10/2018", competition: "Libertadores 2018 - Semifinal", leg: "Vuelta", home: "Palmeiras", away: "Boca Juniors", homeScore: 2, awayScore: 2, note: "Boca paso a la final." },
    { date: "30/10/2018", competition: "Libertadores 2018 - Semifinal", leg: "Vuelta", home: "Gremio", away: "River Plate", homeScore: 1, awayScore: 2, note: "River paso por goles de visitante." },
    { date: "22/10/2019", competition: "Libertadores 2019 - Semifinal", leg: "Vuelta", home: "Boca Juniors", away: "River Plate", homeScore: 1, awayScore: 0, note: "River paso por el global." },
    { date: "13/01/2021", competition: "Libertadores 2020 - Semifinal", leg: "Vuelta", home: "Santos", away: "Boca Juniors", homeScore: 3, awayScore: 0, note: "Santos paso a la final." },
    { date: "12/01/2021", competition: "Libertadores 2020 - Semifinal", leg: "Vuelta", home: "Palmeiras", away: "River Plate", homeScore: 0, awayScore: 2, note: "Palmeiras paso por el global." },
    { date: "05/10/2023", competition: "Libertadores 2023 - Semifinal", leg: "Vuelta", home: "Palmeiras", away: "Boca Juniors", homeScore: 1, awayScore: 1, note: "Boca gano por penales." },
    { date: "22/10/2024", competition: "Libertadores 2024 - Semifinal", leg: "Ida", home: "Atletico Mineiro", away: "River Plate", homeScore: 3, awayScore: 0, note: "Ida de semifinales." },
    { date: "13/09/2015", competition: "Primera Division Argentina 2015", home: "River Plate", away: "Boca Juniors", homeScore: 0, awayScore: 1, note: "Superclasico en el Monumental." },
    { date: "12/09/2015", competition: "Primera Division Argentina 2015", home: "Independiente", away: "Racing", homeScore: 3, awayScore: 0, note: "Clasico de Avellaneda." },
    { date: "18/10/2015", competition: "Primera Division Argentina 2015", home: "Racing", away: "Boca Juniors", homeScore: 3, awayScore: 1, note: "Partido entre grandes." },
    { date: "10/05/2015", competition: "Primera Division Argentina 2015", home: "Independiente", away: "Boca Juniors", homeScore: 1, awayScore: 1, note: "Cruce entre grandes." },
    { date: "10/02/2016", competition: "Supercopa Argentina 2015", home: "Boca Juniors", away: "San Lorenzo", homeScore: 0, awayScore: 4, note: "San Lorenzo campeon." },
    { date: "07/05/2016", competition: "Primera Division Argentina 2016", home: "River Plate", away: "San Lorenzo", homeScore: 5, awayScore: 2, note: "Goleada de River." },
    { date: "14/03/2018", competition: "Supercopa Argentina 2017", home: "Boca Juniors", away: "River Plate", homeScore: 0, awayScore: 2, note: "River campeon en Mendoza." },
    { date: "01/10/2019", competition: "Libertadores 2019 - Semifinal", leg: "Ida", home: "River Plate", away: "Boca Juniors", homeScore: 2, awayScore: 0, note: "Ida de semifinales." },
    { date: "04/03/2021", competition: "Supercopa Argentina 2019", home: "Racing", away: "River Plate", homeScore: 0, awayScore: 5, note: "River campeon." },
    { date: "09/02/2020", competition: "Superliga Argentina 2019-20", home: "Racing", away: "Independiente", homeScore: 1, awayScore: 0, note: "Clasico recordado por la resistencia de Racing." },
    { date: "16/05/2021", competition: "Copa Liga Profesional 2021", home: "Boca Juniors", away: "River Plate", homeScore: 1, awayScore: 1, note: "Boca avanzo por penales." },
    { date: "03/10/2021", competition: "Liga Profesional 2021", home: "River Plate", away: "Boca Juniors", homeScore: 2, awayScore: 1, note: "Superclasico en el Monumental." },
    { date: "11/09/2022", competition: "Liga Profesional 2022", home: "Boca Juniors", away: "River Plate", homeScore: 1, awayScore: 0, note: "Gol de Benedetto." },
    { date: "06/11/2022", competition: "Trofeo de Campeones 2022", home: "Boca Juniors", away: "Racing", homeScore: 1, awayScore: 2, note: "Racing campeon en San Luis." },
    { date: "07/05/2023", competition: "Liga Profesional 2023", home: "River Plate", away: "Boca Juniors", homeScore: 1, awayScore: 0, note: "Gol de penal en el final." },
    { date: "01/10/2023", competition: "Copa Liga Profesional 2023", home: "Boca Juniors", away: "River Plate", homeScore: 0, awayScore: 2, note: "River gano en La Bombonera." },
    { date: "25/02/2024", competition: "Copa Liga Profesional 2024", home: "River Plate", away: "Boca Juniors", homeScore: 1, awayScore: 1, note: "Superclasico de fase regular." },
    { date: "21/04/2024", competition: "Copa Liga Profesional 2024", home: "River Plate", away: "Boca Juniors", homeScore: 2, awayScore: 3, note: "Cuartos de final en Cordoba." },
    { date: "24/02/2024", competition: "Copa Liga Profesional 2024", home: "Independiente", away: "Racing", homeScore: 0, awayScore: 1, note: "Gol de Maravilla Martinez." },
    { date: "14/01/2023", competition: "Supercopa Internacional 2022", home: "Boca Juniors", away: "Racing", homeScore: 1, awayScore: 2, note: "Racing campeon en Abu Dhabi." },
    { date: "06/07/2021", competition: "Copa America 2021 - Semifinal", home: "Argentina", away: "Colombia", homeScore: 1, awayScore: 1, note: "Argentina gano por penales." },
    { date: "03/07/2021", competition: "Copa America 2021 - Cuartos", home: "Argentina", away: "Ecuador", homeScore: 3, awayScore: 0, note: "Messi cerro el partido." },
    { date: "09/07/2024", competition: "Copa America 2024 - Semifinal", home: "Argentina", away: "Canada", homeScore: 2, awayScore: 0, note: "Argentina volvio a la final." },
    { date: "10/07/2024", competition: "Copa America 2024 - Semifinal", home: "Uruguay", away: "Colombia", homeScore: 0, awayScore: 1, note: "Colombia finalista." },
    { date: "06/07/2024", competition: "Copa America 2024 - Cuartos", home: "Colombia", away: "Panama", homeScore: 5, awayScore: 0, note: "Goleada cafetera." },
    { date: "06/07/2024", competition: "Copa America 2024 - Cuartos", home: "Uruguay", away: "Brasil", homeScore: 0, awayScore: 0, note: "Uruguay gano por penales." },
    { date: "29/06/2021", competition: "Euro 2020 - Octavos", home: "Francia", away: "Suiza", homeScore: 3, awayScore: 3, note: "Suiza gano por penales." },
    { date: "19/12/2010", competition: "Mundial de Clubes 2010 - Final", home: "Inter", away: "Mazembe", homeScore: 3, awayScore: 0, note: "Inter campeon mundial." },
    { date: "21/12/2019", competition: "Mundial de Clubes 2019 - Final", home: "Liverpool", away: "Flamengo", homeScore: 1, awayScore: 0, note: "Gol de Firmino." },
    { date: "11/02/2021", competition: "Mundial de Clubes 2020 - Final", home: "Bayern Munich", away: "Tigres", homeScore: 1, awayScore: 0, note: "Bayern campeon." },
    { date: "12/02/2022", competition: "Mundial de Clubes 2021 - Final", home: "Chelsea", away: "Palmeiras", homeScore: 2, awayScore: 1, note: "Chelsea gano en el suplementario." },
    { date: "11/02/2023", competition: "Mundial de Clubes 2022 - Final", home: "Real Madrid", away: "Al Hilal", homeScore: 5, awayScore: 3, note: "Final con muchos goles." },
    { date: "26/11/2022", competition: "Mundial 2022 - Grupo", home: "Argentina", away: "Mexico", homeScore: 2, awayScore: 0, note: "Messi y Enzo sostuvieron a Argentina." },
    { date: "22/12/2023", competition: "Mundial de Clubes 2023 - Final", home: "Manchester City", away: "Fluminense", homeScore: 4, awayScore: 0, note: "City campeon mundial." }
];
