const playerPhotos = {
    "Lionel Messi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg/220px-Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg",
    "Cristiano Ronaldo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Al_Wehda_FC_at_King_Abdul_Aziz_Stadium.jpg/220px-Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Al_Wehda_FC_at_King_Abdul_Aziz_Stadium.jpg",
    "Ángel Di María": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Di_Mar%C3%ADa_Argentina_2022_%28cropped%29.jpg/220px-Di_Mar%C3%ADa_Argentina_2022_%28cropped%29.jpg",
    "Neymar Jr": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Bra-Sui_%281%29.jpg/220px-Bra-Sui_%281%29.jpg",
    "Luis Suárez": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Luis_Su%C3%A1rez_2018.jpg/220px-Luis_Su%C3%A1rez_2018.jpg",
    "James Rodríguez": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/James_Rodr%C3%ADguez_2018.jpg/220px-James_Rodr%C3%ADguez_2018.jpg",
    "Zlatan Ibrahimović": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Zlatan_Ibrahimovi%C3%A1_June_2018.jpg/220px-Zlatan_Ibrahimovi%C3%A1_June_2018.jpg",
    "Ronaldinho": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ronaldinho_11feb2007.jpg/220px-Ronaldinho_11feb2007.jpg",
    "Diego Maradona": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Maradona_by_John_Mathew_Smith.jpg/220px-Maradona_by_John_Mathew_Smith.jpg",
    "Robert Lewandowski": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Robert_Lewandowski_2022_%28cropped%29.jpg/220px-Robert_Lewandowski_2022_%28cropped%29.jpg",
    "Erling Haaland": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Erling_Haaland_2023_%28cropped%29.jpg/220px-Erling_Haaland_2023_%28cropped%29.jpg",
    "Kylian Mbappé": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Kylian_Mbapp%C3%A9_2022.jpg/220px-Kylian_Mbapp%C3%A9_2022.jpg",
    "Luka Modrić": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Luka_Modri%C3%A1_2018.jpg/220px-Luka_Modri%C3%A1_2018.jpg",
    "Karim Benzema": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Karim_Benzema_wearing_Real_Madrid_home_kit_2021-2022.jpg/220px-Karim_Benzema_wearing_Real_Madrid_home_kit_2021-2022.jpg",
    "Enzo Fernández": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Enzo_Fern%C3%A1ndez_2022.jpg/220px-Enzo_Fern%C3%A1ndez_2022.jpg",
    "Julián Álvarez": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Juli%C3%A1n_%C3%81lvarez_2022.jpg/220px-Juli%C3%A1n_%C3%81lvarez_2022.jpg",
    "Emiliano Martínez": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Emiliano_Mart%C3%ADnez_2022.jpg/220px-Emiliano_Mart%C3%ADnez_2022.jpg",
    "Gonzalo Higuaín": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Gonzalo_Higuain_2018.jpg/220px-Gonzalo_Higuain_2018.jpg",
    "Thierry Henry": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Thierry_Henry_mural_Brighton_May_2021.jpg/220px-Thierry_Henry_mural_Brighton_May_2021.jpg",
    "Ronaldo Nazário": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ronaldo_Naz%C3%A1rio_2018.jpg/220px-Ronaldo_Naz%C3%A1rio_2018.jpg",
    "Zinedine Zidane": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_01.jpg/220px-Zinedine_Zidane_by_Tasnim_01.jpg",
    "Carlos Tevez": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tevez_Juventus.jpg/220px-Tevez_Juventus.jpg",
    "Juan Román Riquelme": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Juan_Rom%C3%A1n_Riquelme_2012.jpg/220px-Juan_Rom%C3%A1n_Riquelme_2012.jpg",
    "Andrés Iniesta": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Andr%C3%A9s_Iniesta.jpg/220px-Andr%C3%A9s_Iniesta.jpg",
    "Xavi Hernández": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Xavi_Hernandez_2021.jpg/220px-Xavi_Hernandez_2021.jpg",
    "Sergio Ramos": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sergio_Ramos_2018.jpg/220px-Sergio_Ramos_2018.jpg",
    "Iker Casillas": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Iker_Casillas_2018.jpg/220px-Iker_Casillas_2018.jpg",
    "Manuel Neuer": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Manuel_Neuer_2018.jpg/220px-Manuel_Neuer_2018.jpg",
    "Gianluigi Buffon": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Gianluigi_Buffon_2017.jpg/220px-Gianluigi_Buffon_2017.jpg",
    "Andrea Pirlo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Andrea_Pirlo_2015.jpg/220px-Andrea_Pirlo_2015.jpg",
    "Wayne Rooney": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Wayne_Rooney_2018.jpg/220px-Wayne_Rooney_2018.jpg",
    "David Beckham": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/David_Beckham_2024.jpg/220px-David_Beckham_2024.jpg",
    "Steven Gerrard": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Steven_Gerrard_2015.jpg/220px-Steven_Gerrard_2015.jpg",
    "Frank Lampard": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Frank_Lampard_2015.jpg/220px-Frank_Lampard_2015.jpg",
    "Kaka": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Kak%C3%A1_2017.jpg/220px-Kak%C3%A1_2017.jpg",
    "Paolo Maldini": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Paolo_Maldini_2015.jpg/220px-Paolo_Maldini_2015.jpg",
    "Francesco Totti": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Francesco_Totti_2017.jpg/220px-Francesco_Totti_2017.jpg",
    "Gabriel Batistuta": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Gabriel_Batistuta_2017.jpg/220px-Gabriel_Batistuta_2017.jpg",
    "Hernán Crespo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Hern%C3%A1n_Crespo_2017.jpg/220px-Hern%C3%A1n_Crespo_2017.jpg",
    "Ariel Ortega": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Ariel_Ortega_2011.jpg/220px-Ariel_Ortega_2011.jpg",
    "Juan Sebastián Verón": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Juan_Sebasti%C3%A1n_Ver%C3%B3n_2012.jpg/220px-Juan_Sebasti%C3%A1n_Ver%C3%B3n_2012.jpg",
    "Javier Zanetti": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Javier_Zanetti_2015.jpg/220px-Javier_Zanetti_2015.jpg",
    "Roberto Carlos": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Roberto_Carlos_2018.jpg/220px-Roberto_Carlos_2018.jpg",
    "Cafu": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cafu_2018.jpg/220px-Cafu_2018.jpg",
    "Fabio Cannavaro": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fabio_Cannavaro_2018.jpg/220px-Fabio_Cannavaro_2018.jpg",
    "Alessandro Del Piero": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Alessandro_Del_Piero_2018.jpg/220px-Alessandro_Del_Piero_2018.jpg",
    "Andriy Shevchenko": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Andriy_Shevchenko_2021.jpg/220px-Andriy_Shevchenko_2021.jpg",
    "Luis Figo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Luis_Figo_2018.jpg/220px-Luis_Figo_2018.jpg"
};