const teamLogos = {
    "Barcelona": "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/150px-FC_Barcelona_%28crest%29.svg.png",
    "PSG": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/150px-Paris_Saint-Germain_F.C..svg.png",
    "Inter Miami": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Inter_Miami_CF_logo.svg/150px-Inter_Miami_CF_logo.svg.png",
    "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/150px-Real_Madrid_CF.svg.png",
    "Manchester United": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/150px-Manchester_United_FC_crest.svg.png",
    "Juventus": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Juventus_Turin.svg/150px-Juventus_Turin.svg.png",
    "Benfica": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/SL_Benfica_logo.svg/150px-SL_Benfica_logo.svg.png",
    "Boca Juniors": "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/CABJ_logo.svg/150px-CABJ_logo.svg.png",
    "River Plate": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/River_Plate_crest.svg/150px-River_Plate_crest.svg.png",
    "Manchester City": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/150px-Manchester_City_FC_badge.svg.png",
    "Chelsea": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/150px-Chelsea_FC.svg.png",
    "Liverpool": "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/150px-Liverpool_FC.svg.png",
    "Arsenal": "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/150px-Arsenal_FC.svg.png",
    "Inter": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/FC_Internazionale_Milano_2021.svg/150px-FC_Internazionale_Milano_2021.svg.png",
    "Milan": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/AC_Milan.svg/150px-AC_Milan.svg.png",
    "Atletico de Madrid": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Atletico_Madrid_2017_logo.svg/150px-Atletico_Madrid_2017_logo.svg.png",
    "Bayern Munich": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/150px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
    "Napoli": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SSC_Napoli_logo.svg/150px-SSC_Napoli_logo.svg.png",
    "Ajax": "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/AFC_Ajax_logo.svg/150px-AFC_Ajax_logo.svg.png",
    "Dortmund": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/150px-Borussia_Dortmund_logo.svg.png",
    "Tottenham": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/150px-Tottenham_Hotspur.svg.png",
    "Aston Villa": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/150px-Aston_Villa_FC_crest_%282016%29.svg.png",
    "Athletico Paranaense": "https://upload.wikimedia.org/wikipedia/commons/4/43/Athletico_Paranaense_%28Logo_2019%29.svg",
    "Atletico Nacional": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Atletico_Nacional_Logo.svg",
    "Velez": "https://upload.wikimedia.org/wikipedia/en/thumb/d/db/V%C3%A9lez_Sarsfield_logo.svg/150px-V%C3%A9lez_Sarsfield_logo.svg.png",
    "Independiente": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/CA_Independiente_logo.svg/150px-CA_Independiente_logo.svg.png",
    "San Lorenzo": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/San_Lorenzo_de_Almagro_logo.svg/150px-San_Lorenzo_de_Almagro_logo.svg.png",
    "Racing Club": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/Racing_Club_%28logo%29.svg/150px-Racing_Club_%28logo%29.svg.png",
    "Newell's": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Newell%27s_Old_Boys_logo.svg/150px-Newell%27s_Old_Boys_logo.svg.png",
    "Estudiantes LP": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Estudiantes_de_La_Plata_logo.svg/150px-Estudiantes_de_La_Plata_logo.svg.png",
    "Lanus": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Club_Atl%C3%A9tico_Lan%C3%BAs_logo.svg/150px-Club_Atl%C3%A9tico_Lan%C3%BAs_logo.svg.png",
    "Banfield": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/Club_Atl%C3%A9tico_Banfield_logo.svg/150px-Club_Atl%C3%A9tico_Banfield_logo.svg.png",
    "Porto": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/FC_Porto.svg/150px-FC_Porto.svg.png",
    "Santos": "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Santos_FC_logo.svg/150px-Santos_FC_logo.svg.png",
    "Flamengo": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Flamengo_brazil_logo.svg/150px-Flamengo_brazil_logo.svg.png",
    "Fluminense": "https://upload.wikimedia.org/wikipedia/commons/1/12/Fluminense_Football_Club.svg",
    "Sao Paulo": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Sao_Paulo_FC.svg/150px-Sao_Paulo_FC.svg.png",
    "Palmeiras": "https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Palmeiras_logo.svg/150px-Palmeiras_logo.svg.png",
    "Botafogo": "https://upload.wikimedia.org/wikipedia/commons/5/52/Botafogo_de_Futebol_e_Regatas_logo.svg",
    "Atletico Mineiro": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Clube_Atl%C3%A9tico_Mineiro_logo.svg",
    "Gremio": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Gremio_logo.svg/150px-Gremio_logo.svg.png",
    "Cruzeiro": "https://upload.wikimedia.org/wikipedia/en/thumb/b/bc/Cruzeiro_Esporte_Clube_%28logo%29.svg/150px-Cruzeiro_Esporte_Clube_%28logo%29.svg.png",
    "Internacional": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Sport_Club_Internacional_logo.svg/150px-Sport_Club_Internacional_logo.svg.png",
    "Leicester City": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/150px-Leicester_City_crest.svg.png",
    "Everton": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/150px-Everton_FC_logo.svg.png",
    "Sevilla": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Sevilla_FC_logo.svg/150px-Sevilla_FC_logo.svg.png",
    "Valencia": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valenciacf.svg/150px-Valenciacf.svg.png",
    "Villarreal": "https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Villarreal_CF_logo.svg/150px-Villarreal_CF_logo.svg.png",
    "Betis": "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/150px-Real_betis_logo.svg.png",
    "Zaragoza": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Real_Zaragoza_logo.svg/150px-Real_Zaragoza_logo.svg.png",
    "Mallorca": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Rcd_mallorca.svg/150px-Rcd_mallorca.svg.png",
    "Espanyol": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Rcd_espanyol_logo.svg/150px-Rcd_espanyol_logo.svg.png",
    "Monaco": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/AS_Monaco_FC.svg/150px-AS_Monaco_FC.svg.png",
    "Nice": "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/OGC_Nice_logo.svg/150px-OGC_Nice_logo.svg.png",
    "Marseille": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/Olympique_de_Marseille_logo.svg/150px-Olympique_de_Marseille_logo.svg.png",
    "Lyon": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Olympique_Lyonnais_logo.svg/150px-Olympique_Lyonnais_logo.svg.png",
    "Wolfsburg": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VfL_Wolfsburg_Logo.svg/150px-VfL_Wolfsburg_Logo.svg.png",
    "Lazio": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/S.S._Lazio_badge.svg/150px-S.S._Lazio_badge.svg.png",
    "Fiorentina": "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/ACF_Fiorentina_2022_logo.svg/150px-ACF_Fiorentina_2022_logo.svg.png",
    "Roma": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/AS_Roma_logo_%282017%29.svg/150px-AS_Roma_logo_%282017%29.svg.png",
    "Zenit": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/FC_Zenit_Saint_Petersburg_logo.svg/150px-FC_Zenit_Saint_Petersburg_logo.svg.png",
    "Independiente del Valle": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Club_Social_y_Deportivo_Independiente_Jos%C3%A9_Ter%C3%A1n_logo.png",
    "Mazembe": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/TP_Mazembe_Logo.svg/250px-TP_Mazembe_Logo.svg.png",
    "Tigres": "https://upload.wikimedia.org/wikipedia/commons/c/cf/UANL_Tigres.svg",
    "Al Hilal": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Al-Hilal_Saudi_FC_logo.svg/150px-Al-Hilal_Saudi_FC_logo.svg.png",
    "Al Nassr": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Al-Nassr_FC_logo.svg/150px-Al-Nassr_FC_logo.svg.png"
};
