const teamLogos = {
    "Barcelona": "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/150px-FC_Barcelona_%28crest%29.svg.png",
    "PSG": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/150px-Paris_Saint-Germain_F.C..svg.png",
    "Inter Miami": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Inter_Miami_CF_logo.svg/150px-Inter_Miami_CF_logo.svg.png",
    "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/150px-Real_Madrid_CF.svg.png",
    "Manchester United": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/150px-Manchester_United_FC_crest.svg.png",
    "Juventus": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Juventus_Turin.svg/150px-Juventus_Turin.svg.png",
    "Benfica": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/SL_Benfica_logo.svg/150px-SL_Benfica_logo.svg.png",
    "Boca Juniors": "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/CABJ_logo.svg/150px-CABJ_logo.svg.png",
    "River Plate": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/River_Plate_crest.svg/150px-River_Plate_crest.svg.png",
    "Manchester City": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/150px-Manchester_City_FC_badge.svg.png",
    "Chelsea": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/150px-Chelsea_FC.svg.png",
    "Liverpool": "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/150px-Liverpool_FC.svg.png",
    "Arsenal": "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/150px-Arsenal_FC.svg.png",
    "Inter": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/FC_Internazionale_Milano_2021.svg/150px-FC_Internazionale_Milano_2021.svg.png",
    "Milan": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/AC_Milan.svg/150px-AC_Milan.svg.png",
    "Atletico de Madrid": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Atletico_Madrid_2017_logo.svg/150px-Atletico_Madrid_2017_logo.svg.png",
    "Bayern Munich": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/150px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
    "Napoli": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SSC_Napoli_logo.svg/150px-SSC_Napoli_logo.svg.png",
    "Ajax": "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/AFC_Ajax_logo.svg/150px-AFC_Ajax_logo.svg.png",
    "Dortmund": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/150px-Borussia_Dortmund_logo.svg.png",
    "Tottenham": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/150px-Tottenham_Hotspur.svg.png",
    "Aston Villa": "assets/teams/aston-villa.svg",
    "Athletico Paranaense": "https://upload.wikimedia.org/wikipedia/commons/4/43/Athletico_Paranaense_%28Logo_2019%29.svg",
    "Atletico Nacional": "assets/teams/atletico-nacional.svg",
    "Atlético Nacional": "assets/teams/atletico-nacional.svg",
    "Velez": "https://upload.wikimedia.org/wikipedia/en/thumb/d/db/V%C3%A9lez_Sarsfield_logo.svg/150px-V%C3%A9lez_Sarsfield_logo.svg.png",
    "Independiente": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/CA_Independiente_logo.svg/150px-CA_Independiente_logo.svg.png",
    "San Lorenzo": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/San_Lorenzo_de_Almagro_logo.svg/150px-San_Lorenzo_de_Almagro_logo.svg.png",
    "Racing Club": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/Racing_Club_%28logo%29.svg/150px-Racing_Club_%28logo%29.svg.png",
    "Newell's": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo_Newell%27s_Old_Boys_2019.svg",
    "Estudiantes LP": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Estudiantes_de_La_Plata_logo.svg/150px-Estudiantes_de_La_Plata_logo.svg.png",
    "Lanus": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Club_Atl%C3%A9tico_Lan%C3%BAs_logo.svg/150px-Club_Atl%C3%A9tico_Lan%C3%BAs_logo.svg.png",
    "Banfield": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/Club_Atl%C3%A9tico_Banfield_logo.svg/150px-Club_Atl%C3%A9tico_Banfield_logo.svg.png",
    "Porto": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/FC_Porto.svg/150px-FC_Porto.svg.png",
    "Santos": "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Santos_FC_logo.svg/150px-Santos_FC_logo.svg.png",
    "Flamengo": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Flamengo_brazil_logo.svg/150px-Flamengo_brazil_logo.svg.png",
    "Fluminense": "https://upload.wikimedia.org/wikipedia/commons/1/12/Fluminense_Football_Club.svg",
    "Sao Paulo": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Sao_Paulo_FC.svg/150px-Sao_Paulo_FC.svg.png",
    "Palmeiras": "https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Palmeiras_logo.svg/150px-Palmeiras_logo.svg.png",
    "Botafogo": "https://upload.wikimedia.org/wikipedia/commons/5/52/Botafogo_de_Futebol_e_Regatas_logo.svg",
    "Atletico Mineiro": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Clube_Atl%C3%A9tico_Mineiro_logo.svg",
    "Gremio": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Gremio_logo.svg/150px-Gremio_logo.svg.png",
    "Cruzeiro": "https://upload.wikimedia.org/wikipedia/en/thumb/b/bc/Cruzeiro_Esporte_Clube_%28logo%29.svg/150px-Cruzeiro_Esporte_Clube_%28logo%29.svg.png",
    "Internacional": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Sport_Club_Internacional_logo.svg/150px-Sport_Club_Internacional_logo.svg.png",
    "Leicester City": "assets/teams/leicester-city.svg",
    "Everton": "assets/teams/everton.svg",
    "Sevilla": "assets/teams/sevilla.png",
    "Valencia": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valenciacf.svg/150px-Valenciacf.svg.png",
    "Villarreal": "https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Villarreal_CF_logo.svg/150px-Villarreal_CF_logo.svg.png",
    "Betis": "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/150px-Real_betis_logo.svg.png",
    "Zaragoza": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Real_Zaragoza_logo.svg/150px-Real_Zaragoza_logo.svg.png",
    "Mallorca": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Rcd_mallorca.svg/150px-Rcd_mallorca.svg.png",
    "Espanyol": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Rcd_espanyol_logo.svg/150px-Rcd_espanyol_logo.svg.png",
    "Monaco": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/AS_Monaco_FC.svg/150px-AS_Monaco_FC.svg.png",
    "Nice": "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/OGC_Nice_logo.svg/150px-OGC_Nice_logo.svg.png",
    "Marseille": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/Olympique_de_Marseille_logo.svg/150px-Olympique_de_Marseille_logo.svg.png",
    "Lyon": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Olympique_Lyonnais_logo.svg/150px-Olympique_Lyonnais_logo.svg.png",
    "Wolfsburg": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VfL_Wolfsburg_Logo.svg/150px-VfL_Wolfsburg_Logo.svg.png",
    "Lazio": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/S.S._Lazio_badge.svg/150px-S.S._Lazio_badge.svg.png",
    "Fiorentina": "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/ACF_Fiorentina_2022_logo.svg/150px-ACF_Fiorentina_2022_logo.svg.png",
    "Roma": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/AS_Roma_logo_%282017%29.svg/150px-AS_Roma_logo_%282017%29.svg.png",
    "Zenit": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/FC_Zenit_Saint_Petersburg_logo.svg/150px-FC_Zenit_Saint_Petersburg_logo.svg.png",
    "Independiente del Valle": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Club_Social_y_Deportivo_Independiente_Jos%C3%A9_Ter%C3%A1n_logo.png",
    "Mazembe": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/TP_Mazembe_Logo.svg/250px-TP_Mazembe_Logo.svg.png",
    "Tigres": "https://upload.wikimedia.org/wikipedia/commons/c/cf/UANL_Tigres.svg",
    "Al Hilal": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Al-Hilal_Saudi_FC_logo.svg/150px-Al-Hilal_Saudi_FC_logo.svg.png",
    "Al Nassr": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Al-Nassr_FC_logo.svg/150px-Al-Nassr_FC_logo.svg.png",
    "Rosario Central": "https://r2.thesportsdb.com/images/media/team/badge/y6q1ds1769660256.png",
    "Groningen": "https://r2.thesportsdb.com/images/media/team/badge/f36qnp1666107447.png",
    "Al-Rayyan": "https://r2.thesportsdb.com/images/media/team/badge/hvb3r41653090047.png",
    "Querétaro": "https://r2.thesportsdb.com/images/media/team/badge/024n481781543211.png",
    "Shanghai Shenhua": "https://r2.thesportsdb.com/images/media/team/badge/p0r1bj1654266974.png",
    "Stuttgart": "https://r2.thesportsdb.com/images/media/team/badge/yppyux1473454085.png",
    "Envigado": "https://r2.thesportsdb.com/images/media/team/badge/h1x0ic1629122571.png",
    "Millonarios": "https://r2.thesportsdb.com/images/media/team/badge/mc73ix1629122587.png",
    "Watford": "https://r2.thesportsdb.com/images/media/team/badge/rsuswy1448813519.png",
    "Palermo": "https://r2.thesportsdb.com/images/media/team/badge/zi1tb01579708939.png",
    "Malmö FF": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Malmo_FF_logo.svg/330px-Malmo_FF_logo.svg.png",
    "Udinese": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Udinese_Calcio_logo.svg/330px-Udinese_Calcio_logo.svg.png",
    "Kashima Antlers": "https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Kashima_Antlers.svg/330px-Kashima_Antlers.svg.png",
    "Vélez Sarsfield": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Escudo%20del%20Club%20Atl%C3%A9tico%20V%C3%A9lez%20Sarsfield.svg",
    "Defensores de Belgrano": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Defensores_de_Belgrano_Logo.svg/330px-Defensores_de_Belgrano_Logo.svg.png",
    "Al Ain": "https://r2.thesportsdb.com/images/media/team/badge/0w2bk51747334688.png",
    "Al-Ahli": "https://r2.thesportsdb.com/images/media/team/badge/1bbtgb1755192301.png",
    "Al-Arabi": "https://r2.thesportsdb.com/images/media/team/badge/8mmlwm1745434332.png",
    "Alverca": "https://r2.thesportsdb.com/images/media/team/badge/6ljryf1691990098.png",
    "Ancona": "https://r2.thesportsdb.com/images/media/team/badge/72m3br1628795789.png",
    "Antalyaspor": "https://r2.thesportsdb.com/images/media/team/badge/vqoral1601669436.png",
    "Atlante": "https://r2.thesportsdb.com/images/media/team/badge/wcf2r51754018201.png",
    "Baniyas": "https://r2.thesportsdb.com/images/media/team/badge/ps3a4d1578859691.png",
    "Başakşehir": "https://r2.thesportsdb.com/images/media/team/badge/895mqt1685993958.png",
    "Brest": "https://r2.thesportsdb.com/images/media/team/badge/z69be41598797026.png",
    "Brøndby": "https://r2.thesportsdb.com/images/media/team/badge/ywswyw1473535498.png",
    "Bryne": "https://r2.thesportsdb.com/images/media/team/badge/e3t5fg1690695712.png",
    "Bunyodkor": "https://r2.thesportsdb.com/images/media/team/badge/crm3u81583080177.png",
    "Cannes": "https://r2.thesportsdb.com/images/media/team/badge/1120tb1690570715.png",
    "Consadole Sapporo": "https://r2.thesportsdb.com/images/media/team/badge/it2q671578253723.png",
    "Cosenza": "https://r2.thesportsdb.com/images/media/team/badge/u6z5yu1656094382.png",
    "Dallas Burn": "https://r2.thesportsdb.com/images/media/team/badge/vxy8xy1602103187.png",
    "Dukla Prague": "https://r2.thesportsdb.com/images/media/team/badge/n950g01578837378.png",
    "Ferro Carril Oeste": "https://r2.thesportsdb.com/images/media/team/badge/qv5l9p1578822488.png",
    "Gladbach": "https://r2.thesportsdb.com/images/media/team/badge/sysurw1473453380.png",
    "Hércules": "https://r2.thesportsdb.com/images/media/team/badge/3evl161711252098.png",
    "Hvidovre": "https://r2.thesportsdb.com/images/media/team/badge/d42gnh1581257444.png",
    "Independiente Rivadavia": "https://r2.thesportsdb.com/images/media/team/badge/qgzi2b1769406125.png",
    "Johor Darul Ta'zim": "https://r2.thesportsdb.com/images/media/team/badge/83yb6b1588360236.png",
    "Kaiserslautern": "https://r2.thesportsdb.com/images/media/team/badge/jghax31740165513.png",
    "Kawasaki Frontale": "https://r2.thesportsdb.com/images/media/team/badge/c6pot51578239112.png",
    "Konyaspor": "https://r2.thesportsdb.com/images/media/team/badge/rxwptr1448203413.png",
    "LASK Linz": "https://r2.thesportsdb.com/images/media/team/badge/oox26l1683556395.png",
    "Leganés": "https://r2.thesportsdb.com/images/media/team/badge/tm0adr1616443898.png",
    "Logroñés": "https://commons.wikimedia.org/wiki/Special:Redirect/file/CD_Logro%C3%B1%C3%A9s_logo.svg",
    "Lumezzane": "https://r2.thesportsdb.com/images/media/team/badge/ltgfqd1691578719.png",
    "MetroStars": "https://r2.thesportsdb.com/images/media/team/badge/suytvy1473536462.png",
    "Molde": "https://r2.thesportsdb.com/images/media/team/badge/apziyg1534866527.png",
    "Montreal Impact": "https://r2.thesportsdb.com/images/media/team/badge/livdl31679344925.png",
    "Monza": "https://r2.thesportsdb.com/images/media/team/badge/bxearg1603170113.png",
    "Nancy": "https://r2.thesportsdb.com/images/media/team/badge/ve39pj1547899643.png",
    "Nantes": "https://r2.thesportsdb.com/images/media/team/badge/mla9x61678808018.png",
    "Padova": "https://r2.thesportsdb.com/images/media/team/badge/hklo0i1579724992.png",
    "Piacenza": "https://r2.thesportsdb.com/images/media/team/badge/l3q31k1697951057.png",
    "Pisa": "https://r2.thesportsdb.com/images/media/team/badge/2eso9w1579708309.png",
    "Portsmouth": "https://r2.thesportsdb.com/images/media/team/badge/j13pfe1601726274.png",
    "Preston North End": "https://r2.thesportsdb.com/images/media/team/badge/wqtwvw1448811512.png",
    "Rangers": "https://r2.thesportsdb.com/images/media/team/badge/ti24j61614290048.png",
    "Ravenna": "https://r2.thesportsdb.com/images/media/team/badge/l80c6j1724118398.png",
    "RB Salzburg": "https://r2.thesportsdb.com/images/media/team/badge/nc2cua1781541639.png",
    "Real Madrid B": "https://r2.thesportsdb.com/images/media/team/badge/djtemm1639480207.png",
    "Real Murcia": "https://r2.thesportsdb.com/images/media/team/badge/zoo96h1747995489.png",
    "Real Oviedo": "https://r2.thesportsdb.com/images/media/team/badge/yuwqus1447590681.png",
    "Recreativo": "https://r2.thesportsdb.com/images/media/team/badge/s2pii11626207918.png",
    "Red Star Belgrade": "https://r2.thesportsdb.com/images/media/team/badge/osgmbz1781157114.png",
    "Reggina": "https://r2.thesportsdb.com/images/media/team/badge/5zh7bz1603170133.png",
    "Rennes": "https://r2.thesportsdb.com/images/media/team/badge/ypturx1473504818.png",
    "Saint-Étienne": "https://r2.thesportsdb.com/images/media/team/badge/m4ej831656423694.png",
    "Santa Cruz": "https://r2.thesportsdb.com/images/media/team/badge/vvusuv1464886343.png",
    "Sao Caetano": "https://r2.thesportsdb.com/images/media/team/badge/e72hdi1593453914.png",
    "Shanghai SIPG": "https://r2.thesportsdb.com/images/media/team/badge/d9evs91776534441.png",
    "Sion": "https://r2.thesportsdb.com/images/media/team/badge/gzpfmv1689085319.png",
    "Sunderland": "https://r2.thesportsdb.com/images/media/team/badge/tprtus1448813498.png",
    "Swindon Town": "https://r2.thesportsdb.com/images/media/team/badge/uwsyup1424033445.png",
    "Tokyo Verdy": "https://r2.thesportsdb.com/images/media/team/badge/9dqjaw1590071011.png",
    "Vasco da Gama": "https://r2.thesportsdb.com/images/media/team/badge/ynqlxo1630521109.png",
    "Venezia": "https://r2.thesportsdb.com/images/media/team/badge/vbiget1781026964.png",
    "Vicenza": "https://r2.thesportsdb.com/images/media/team/badge/fj8twm1569164066.png",
    "Vissel Kobe": "https://r2.thesportsdb.com/images/media/team/badge/2axjch1578239819.png",
    "Vitória": "https://r2.thesportsdb.com/images/media/team/badge/tysrrx1473538156.png",
    "Wanderers": "https://r2.thesportsdb.com/images/media/team/badge/3i6k5s1766114857.png",
    "Znicz Pruszków": "https://r2.thesportsdb.com/images/media/team/badge/lm3ts01698554359.png",
    "Atlético Celaya": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Atletico%20Celaya.png",
    "Barcelona B": "assets/teams/barcelona.svg",
    "Blšany": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Chmel%20Blsany.png",
    "Gladsaxe-Hero": "https://file.dbu.dk/images/club/1035/Gladsaxe-Hero_BK.png",
    "Haarlem": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/HFC_Haarlem_%28logo%29.svg/330px-HFC_Haarlem_%28logo%29.svg.png",
    "Kabuscorp": "https://r2.thesportsdb.com/images/media/team/badge/n3dhc91653071489.png",
    "Leffe": "https://r2.thesportsdb.com/images/media/team/badge/uvqqrs1429975374.png",
    "Racing Paris": "https://r2.thesportsdb.com/images/media/team/badge/tqkfoz1741603466.png",
    "Salgueiros": "https://r2.thesportsdb.com/images/media/team/badge/w4xc8n1732594980.png",
    "San Diego Sockers": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Sandiego%20sockers%20logo.png",
    "Talleres RE": "https://r2.thesportsdb.com/images/media/team/badge/f08ex91690264922.png",
    "Uniao Sao Joao": "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Uni%C3%A3o_S%C3%A3o_Jo%C3%A3o_Esporte_Clube_logo.svg/330px-Uni%C3%A3o_S%C3%A3o_Jo%C3%A3o_Esporte_Clube_logo.svg.png",
    "Vecindario": "https://commons.wikimedia.org/wiki/Special:Redirect/file/UD%20Vecindario.gif",
    "Cruzeiro": "https://r2.thesportsdb.com/images/media/team/badge/upsvvu1473538059.png",
    "Sao Paulo": "https://r2.thesportsdb.com/images/media/team/badge/sxpupx1473538135.png",
    "São Paulo": "https://r2.thesportsdb.com/images/media/team/badge/sxpupx1473538135.png",
    "Orlando City": "https://r2.thesportsdb.com/images/media/team/badge/qyppxw1423832326.png",
    "Hellas Verona": "https://r2.thesportsdb.com/images/media/team/badge/p6camf1593457737.png",
    "Verona": "https://r2.thesportsdb.com/images/media/team/badge/p6camf1593457737.png",
    "Chemnitzer FC": "https://r2.thesportsdb.com/images/media/team/badge/cxc1gc1579106325.png",
    "Napoli": "https://r2.thesportsdb.com/images/media/team/badge/l8qyxv1742982541.png",
    "Delhi Dynamos": "https://r2.thesportsdb.com/images/media/team/badge/ljpjmn1693034492.png",
    "Villarreal": "https://r2.thesportsdb.com/images/media/team/badge/vrypqy1473503073.png",
    "Ajax": "https://r2.thesportsdb.com/images/media/team/badge/zg9tii1755495289.png",
    "Genoa": "https://r2.thesportsdb.com/images/media/team/badge/52s8dn1655553600.png",
    "Benfica": "https://r2.thesportsdb.com/images/media/team/badge/hj4kyc1781152436.png",
    "Inter Miami": "https://r2.thesportsdb.com/images/media/team/badge/m4it3e1602103647.png",
    "Velez": "https://r2.thesportsdb.com/images/media/team/badge/jo98m71517769587.png",
    "Vélez": "https://r2.thesportsdb.com/images/media/team/badge/jo98m71517769587.png",
    "Vélez Sarsfield": "https://r2.thesportsdb.com/images/media/team/badge/jo98m71517769587.png",
    "Platense": "https://r2.thesportsdb.com/images/media/team/badge/lbs14n1769317149.png",
    "Caen": "https://r2.thesportsdb.com/images/media/team/badge/uwuuqu1467461847.png",
    "Dundee FC": "https://r2.thesportsdb.com/images/media/team/badge/tlei9x1750743461.png",
    "Qatar SC": "https://r2.thesportsdb.com/images/media/team/badge/3c07ob1774579037.png",
    "Newell's": "https://r2.thesportsdb.com/images/media/team/badge/23aftf1580842633.png",
    "Basel": "https://r2.thesportsdb.com/images/media/team/badge/xppxwr1473791183.png",
    "Banfield": "https://r2.thesportsdb.com/images/media/team/badge/c2ea011775756104.png",
    "Monaco": "https://r2.thesportsdb.com/images/media/team/badge/exjf5l1678808044.png",
    "Feyenoord": "https://r2.thesportsdb.com/images/media/team/badge/uturtx1473534803.png",
    "Sydney FC": "https://r2.thesportsdb.com/images/media/team/badge/utgq8z1546110747.png",
    "Nice": "https://r2.thesportsdb.com/images/media/team/badge/msy7ly1621593859.png",
    "Marseille": "https://r2.thesportsdb.com/images/media/team/badge/c6bazh1779212287.png",
    "Wolfsburg": "https://r2.thesportsdb.com/images/media/team/badge/ci9trv1778399557.png",
    "Mallorca": "https://r2.thesportsdb.com/images/media/team/badge/ssptsx1473503730.png",
    "UNAM": "https://upload.wikimedia.org/wikipedia/en/b/b7/Club_Universidad_Nacional_logo.svg",
    "Pumas UNAM": "https://upload.wikimedia.org/wikipedia/en/b/b7/Club_Universidad_Nacional_logo.svg",
    "Sparta Prague": "https://r2.thesportsdb.com/images/media/team/badge/j00qct1718287150.png",
    "Leeds United": "https://r2.thesportsdb.com/images/media/team/badge/jcgrml1756649030.png",
    "Emirates Club": "https://r2.thesportsdb.com/images/media/team/badge/t7k92p1625755733.png",
    "Barnet FC": "https://r2.thesportsdb.com/images/media/team/badge/wyqvwq1447531659.png",
    "Chennaiyin FC": "https://r2.thesportsdb.com/images/media/team/badge/g5rypn1583254717.png",
    "Miami FC": "https://r2.thesportsdb.com/images/media/team/badge/ow77dj1595154153.png",
    "Adelaide United": "https://r2.thesportsdb.com/images/media/team/badge/wpyuwv1473454602.png",
    "Stoke City": "https://r2.thesportsdb.com/images/media/team/badge/lz89v21781718914.png",
    "Swansea City": "https://r2.thesportsdb.com/images/media/team/badge/474rco1686920744.png",
    "Karlsruher SC": "https://r2.thesportsdb.com/images/media/team/badge/l784ls1696006504.png",
    "Zaragoza": "https://r2.thesportsdb.com/images/media/team/badge/sxpwxs1473503702.png",
    "Lyon": "https://r2.thesportsdb.com/images/media/team/badge/blk9771656932845.png",
    "Bologna": "https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png",
    "Cagliari": "https://r2.thesportsdb.com/images/media/team/badge/wvsvxt1447534471.png",
    "Belgrano": "https://r2.thesportsdb.com/images/media/team/badge/0twgzi1517768087.png",
    "Como": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Calcio_Como_-_logo_%28Italy%2C_2019-%29.svg/330px-Calcio_Como_-_logo_%28Italy%2C_2019-%29.svg.png",
    "Málaga": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/M%C3%A1laga_CF.svg/330px-M%C3%A1laga_CF.svg.png",
    "Malaga": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/M%C3%A1laga_CF.svg/330px-M%C3%A1laga_CF.svg.png",
    "América MG": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Escudo_oficial_do_Am%C3%A9rica_Futebol_Clube.svg/330px-Escudo_oficial_do_Am%C3%A9rica_Futebol_Clube.svg.png",
    "America MG": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Escudo_oficial_do_Am%C3%A9rica_Futebol_Clube.svg/330px-Escudo_oficial_do_Am%C3%A9rica_Futebol_Clube.svg.png",
    "Deportivo": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/RC_Deportivo_A_Coru%C3%B1a_logo_2026.svg/330px-RC_Deportivo_A_Coru%C3%B1a_logo_2026.svg.png",
    "Logroñés": "https://upload.wikimedia.org/wikipedia/en/3/34/SD_Logro%C3%B1%C3%A9s_logo.png",
    "Atlético Celaya": "https://fr.wikipedia.org/wiki/Special:Redirect/file/Atletico%20Celaya.png",
    "Blšany": "https://fr.wikipedia.org/wiki/Special:Redirect/file/Chmel%20Blsany.png",
    "Pune City": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/FC_Pune_City.svg/330px-FC_Pune_City.svg.png",
    "Botafogo-SP": "https://fr.wikipedia.org/wiki/Special:Redirect/file/Botafogo%20Futebol%20Clube%20(Ribeir%C3%A3o%20Preto)%20(logo).svg",
    "Vecindario": "https://fr.wikipedia.org/wiki/Special:Redirect/file/UD%20Vecindario.gif",
    "Zenit": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/FC_Zenit_Saint_Petersburg_crest.svg/330px-FC_Zenit_Saint_Petersburg_crest.svg.png",
    "Betis": "https://r2.thesportsdb.com/images/media/team/badge/2oqulv1663245386.png",
    "Espanyol": "https://r2.thesportsdb.com/images/media/team/badge/867nzz1681703222.png",
    "Sampdoria": "https://r2.thesportsdb.com/images/media/team/badge/pr6co21655592769.png",
    "Celta de Vigo": "https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png",
    "Rayo Vallecano": "https://r2.thesportsdb.com/images/media/team/badge/nzhu941655595465.png",
    "Bahia": "https://r2.thesportsdb.com/images/media/team/badge/xuvtsv1473539308.png",
    "Birmingham": "https://r2.thesportsdb.com/images/media/team/badge/wufs551672950865.png",
    "Birmingham City": "https://r2.thesportsdb.com/images/media/team/badge/wufs551672950865.png",
    "West Ham": "https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png",
    "West Ham United": "https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png",
    "Juventude": "https://r2.thesportsdb.com/images/media/team/badge/1ntter1766506778.png",
    "Torino": "https://r2.thesportsdb.com/images/media/team/badge/xxprty1448806802.png",
    "Corinthians": "https://r2.thesportsdb.com/images/media/team/badge/vvuvps1473538042.png",
    "América": "https://r2.thesportsdb.com/images/media/team/badge/amy1xs1581857392.png",
    "America": "https://r2.thesportsdb.com/images/media/team/badge/amy1xs1581857392.png",
    "Fulham": "https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png",
    "Newcastle": "https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png",
    "Newcastle United": "https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png",
    "Brescia": "https://r2.thesportsdb.com/images/media/team/badge/k0qhbd1566756266.png",
    "NYCFC": "https://r2.thesportsdb.com/images/media/team/badge/m9vis71735140655.png",
    "New York City FC": "https://r2.thesportsdb.com/images/media/team/badge/m9vis71735140655.png",
    "Bayer Leverkusen": "https://r2.thesportsdb.com/images/media/team/badge/3x9k851726760113.png",
    "Adana Demirspor": "https://r2.thesportsdb.com/images/media/team/badge/hewt221626264325.png",
    "AEK Athens": "https://r2.thesportsdb.com/images/media/team/badge/4nogst1602773624.png",
    "Alavés": "https://r2.thesportsdb.com/images/media/team/badge/mfn99h1734673842.png",
    "Alaves": "https://r2.thesportsdb.com/images/media/team/badge/mfn99h1734673842.png",
    "Anzhi": "https://r2.thesportsdb.com/images/media/team/badge/tqsyvq1447540564.png",
    "Anzhi Makhachkala": "https://r2.thesportsdb.com/images/media/team/badge/tqsyvq1447540564.png",
    "Eintracht Frankfurt": "https://r2.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png",
    "All Boys": "https://r2.thesportsdb.com/images/media/team/badge/zo4vm01578824142.png",
    "Mogi Mirim": "https://r2.thesportsdb.com/images/media/team/badge/mljx5a1515530538.png"
};
